name: Weather Journal App
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        env: 
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
        run: make clean build deploy
      - name: Run tests
        shell: bash
        env: 
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
        run: make test
      - name: Cleanup
        run: make clean        
          

        