name: Weather Journal App
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm i puppeteer-core
          npm install cucumber --save-dev
      - name: Run tests
        run: |
          npm test
          apt-get install -y tree
          tree

        