name: Weather Journal App
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup & run Cucumber
        run: |
          npm install cucumber --save-dev
          npm test

        