name: Weather Journal App
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make clean build deploy
      - name: Run tests
        run: make test
      - name: Cleanup
        run: make clean
          
          

        